language: python
python:
  - 3.5.2
  - 3.6.4
  - 3.7.0
  - 3.7.1
  - 3.7.2
  - 3.7.3
  - 3.7.4
  - 3.7.5
  - 3.7.6
  - 3.7.7
  - 3.8.0
  - 3.8.1
  - 3.8.2
  - 3.8.3
script:
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_pg.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_mysql.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_sqlite.py python setup.py test
services:
  - postgresql
  - mysql
before_script:
  - psql --version
  - psql -c 'create database jardin_test;' -U postgres
  - mysql -e 'CREATE DATABASE jardin_test;'
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5432
